target("zabato_lua")
    set_kind("static")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_includedirs("src", {public = false})
    add_includedirs("../../../ext/lua", {public = true})
    add_files("../../../ext/lua/*.c")
    remove_files("../../../ext/lua/lua.c", "../../../ext/lua/luac.c", "../../../ext/lua/onelua.c")

    add_deps("zabato")
    add_cxxflags("-fno-rtti")
    set_languages("c++23")
    add_packages("tinyxml2")