#pragma once

#include <imgui.h>
#include <zabato/gpu.hpp>
#include <zabato/window.hpp>

namespace zabato::imgui
{
/**
 * @brief Initializes the ImGui binding for the Zabato engine.
 *
 * Sets up the ImGui context, installs input callbacks on the provided window,
 * and initializes the GPU renderer resources (font textures, etc.).
 *
 * @param win Pointer to the application window where input events will be
 * captured.
 */
void init(window *win);

/**
 * @brief Shuts down the ImGui binding.
 *
 * Cleans up the ImGui context, removes installed callbacks from the window,
 * and frees GPU resources.
 */
void shutdown();

/**
 * @brief Starts a new ImGui frame.
 *
 * Updates the ImGui IO state with the current time (delta time), mouse
 * position, display size, and processes pending input events. Must be called at
 * the beginning of the frame, before any ImGui UI commands.
 */
void new_frame();

/**
 * @brief Renders the ImGui draw data using the Zabato GPU API.
 *
 * This function handles setting up the GPU state (scissor test, blending, etc.)
 * and executing the draw commands generated by ImGui.
 *
 * @param draw_data Pointer to the ImDrawData structure retrieved via
 * `ImGui::GetDrawData()`.
 */
void render_draw_data(struct ImDrawData *draw_data);

/**
 * @brief Structure representing a custom settings handler for ImGui.
 *
 * This structure abstracts the ImGuiSettingsHandler, allowing users to register
 * custom handlers for saving and loading settings from the .ini file without
 * including imgui_internal.h.
 */
struct settings_handler
{
    const char *type_name;
    uint32_t type_hash;
    void *user_data;

    void *(*read_open_fn)(void *user_data, const char *name);
    void (*read_line_fn)(void *user_data, void *entry, const char *line);
    void (*write_all_fn)(void *user_data, struct ImGuiTextBuffer *buf);
};

/**
 * @brief Registers a custom settings handler.
 *
 * @param handler The settings handler to register.
 */
void add_settings_handler(const settings_handler &handler);

/**
 * @brief Computes a hash for the given string, compatible with ImGui's hashing.
 *
 * @param str The string to hash.
 * @return uint32_t The computed hash.
 */
uint32_t hash_string(const char *str);

/**
 * @brief Callback function type for custom atlas packing.
 *
 * @param pixels The RGBA32 pixel buffer of the font atlas.
 * @param width The width of the atlas.
 * @param height The height of the atlas.
 * @param user_data User-provided data pointer.
 */
using atlas_pack_callback = void (*)(unsigned char *pixels,
                                     int width,
                                     int height,
                                     void *user_data);

/**
 * @brief Sets the callback for custom atlas packing.
 *
 * This callback is invoked immediately after the font atlas is built but before
 * it is uploaded to the GPU. This allows for writing custom glyph data (e.g.
 * icons) directly into the atlas.
 *
 * @param cb The callback function.
 * @param user_data Data to pass to the callback.
 */
void set_atlas_pack_callback(atlas_pack_callback cb, void *user_data);

} // namespace zabato::imgui
