#pragma once

#include <imgui.h>
#include <zabato/gpu.hpp>
#include <zabato/window.hpp>

namespace zabato::imgui
{
/**
 * @brief Initializes the ImGui binding for the Zabato engine.
 *
 * Sets up the ImGui context, installs input callbacks on the provided window,
 * and initializes the GPU renderer resources (font textures, etc.).
 *
 * @param win Pointer to the application window where input events will be
 * captured.
 */
void init(window *win);

/**
 * @brief Shuts down the ImGui binding.
 *
 * Cleans up the ImGui context, removes installed callbacks from the window,
 * and frees GPU resources.
 */
void shutdown();

/**
 * @brief Starts a new ImGui frame.
 *
 * Updates the ImGui IO state with the current time (delta time), mouse
 * position, display size, and processes pending input events. Must be called at
 * the beginning of the frame, before any ImGui UI commands.
 */
void new_frame();

/**
 * @brief Renders the ImGui draw data using the Zabato GPU API.
 *
 * This function handles setting up the GPU state (scissor test, blending, etc.)
 * and executing the draw commands generated by ImGui.
 *
 * @param draw_data Pointer to the ImDrawData structure retrieved via
 * `ImGui::GetDrawData()`.
 */
void render_draw_data(struct ImDrawData *draw_data);

} // namespace zabato::imgui
