target("libberg")
    set_kind("static")
    set_languages("c99")
    add_files("berg.c")
    add_includedirs("include", {public = true})
    add_defines("BERG_STATIC", {public = true})
    set_basename("libberg")

target("cli_berg")
    set_kind("binary")
    set_languages("c++23")
    add_files("main.c")
    
    add_deps("libberg")
    set_basename("berg")